### ISSUE TITLE
Code in previsualization gets an additional border and padding

### ISSUE THREAD

**Issue by kortatu** [kortatu/WritingSwarm#10]
Only the  `<pre>` tag should contain border and padding, not the code inside:

```css
.textzone code {
    /* background-color: #f8f8f8; */
    /* border-color: #dfdfdf; */
    /* border-style: solid; */
    /* border-width: 1px; */
    color: #333;
    font-family: Consolas,"Liberation Mono",Courier,monospace;
    font-weight: normal;
    /* padding: 0.125rem 0.3125rem 0.0625rem;
}
```
